import type { Metadata } from "next";

import "./globals.css";
import { Lato } from "next/font/google";
import Footer from "@/components/layout/Footer";

const lato = Lato({
  weight: ["300", "400", "700", "900"], // Include multiple weights
  subsets: ["latin"], // Optimize character subset
  display: "swap", // Ensures text is visible during font loading
  variable: "--font-lato", // Optional: for Tailwind CSS integration
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lato.className} antialiased`}
        suppressHydrationWarning
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
